### ISSUE TITLE
wdrożyć failowanie depu na produkcje jak jest cokolwiek na AB

### ISSUE THREAD

**Issue by wiktorschmidt** [netguru/netguru#14]

**Comment by lubieniebieski** [comment]
osiągalne w ogóle?

**Comment by madsheep** [comment]
nie osiągalne tylko konieczne. Jak coś musi być to da się zrobić.

**Comment by lubieniebieski** [comment]
ok, just asking, bo jak w masz w jakiś projektach też błędy z api na airbrake (czy też inne nie zawsze zależne od projektu), to wtedy by je trzeba odfiltrować jakoś, right?

**Comment by lukkry** [comment]
https://github.com/netguru/netguru/pull/20

**Comment by mamut** [comment]
Solved by #20
