### ISSUE TITLE
Upiększenie strony z hasłem, HTML + CSS

### ISSUE THREAD

**Issue by lukkry** [netguru/netguru#21]

**Comment by lubieniebieski** [comment]
coś więcej na ten temat?

**Comment by lukkry** [comment]
chodzi o to aby HTML pochodzący z Block Middleware wyglądał ładnie, obecnie mamy:

``` html
Password: 
<form action="" method="post">
  <input type="password" name="code" />
  <input type="submit" />
</form>
```

Myślę tutaj o czymś bardzo prostym, podpięciu twitter bootstrap i wyśrodkowaniu całości.
Będzie też okazja aby wywalić html do osobnego pliku.
