### ISSUE TITLE
Not informative erro on deploy.

### ISSUE THREAD

**Issue by sufleR** [netguru/netguru#34]
```
/home/dashguru/app/current/tmp/projects_bundle/ruby/2.0.0/bundler/gems/netguru-85e47ac28ad2/lib/netguru/rollbar.rb:19:in `exec_capistrano_task': [rollbar] Computer says no! - There are 1 errors. (RuntimeError)
```

I think that it should inform that there are unresolved errors registered in rollbar.
When I saw this error I was searching error in configs and netguru gem at first.

**Comment by madsheep** [comment]
PR? Changing message is easy ;)
